apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: orchestrator
  labels:
    app: application
spec:
  selector:
    matchLabels:
      app: application
  replicas: 1
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: orchestrator
        image: orchestratorservices:v0.0.3
        imagePullPolicy: IfNotPresent
        env:
          - name: ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: aws_access_key_id
          - name: SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: aws_secret_access_key
        volumeMounts:
        - name: log
          mountPath: /logs
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: log
        emptyDir: {}