apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: orchestrator
  labels:
    app: Database
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis/redisinsight:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: redisvolume
          mountPath: /data
        ports:
        - containerPort: 6379
          protocol: TCP
      volumes:
      - name: redisvolume
        emptyDir: {}
